import type { Metadata } from "next";
import { Lora } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

const madelyn = localFont({
  src: [
    {
      path: "../../public/fonts/Madelyn.woff",
      weight: "400",
    },
  ],
  variable: "--font-madelyn",
});


const lora = Lora({ subsets: ["latin"], variable: "--font-lora" });

export const metadata: Metadata = {
  title: "Tayná Rau - Psicolóloga",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${madelyn.variable} ${lora.variable}`}>
      <body>{children}</body>
    </html>
  );
}
